### ISSUE TITLE
Exception encountered when loading plugin

### ISSUE THREAD

**Issue by jnijland** [muehre/container-manager#4]
When the plugin is loaded, even in his default set-up, ran in Docker with docker compose on my own machine, I receive the following error:

```
09:59:20 [WARNING] Exception encountered when loading plugin: DockerizedCraft
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.<clinit>(JerseyDockerCmdExecFactory.java:115)
	at com.github.dockerjava.core.DockerClientBuilder.getDefaultDockerCmdExecFactory(DockerClientBuilder.java:35)
	at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:47)
	at de.craftmania.dockerizedcraft.container.inspector.client.DockerClientFactory.get(DockerClientFactory.java:58)
	at de.craftmania.dockerizedcraft.container.inspector.client.DockerClientFactory.getByConfiguration(DockerClientFactory.java:12)
	at de.craftmania.dockerizedcraft.container.inspector.ContainerInspector.<init>(ContainerInspector.java:29)
	at de.craftmania.dockerizedcraft.DockerizedCraft.bootstrapContainerInspector(DockerizedCraft.java:127)
	at de.craftmania.dockerizedcraft.DockerizedCraft.onEnable(DockerizedCraft.java:63)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by ArnaudLier** [comment]
Still have this issue ? Unable to reproduce.
